version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: depart_chat
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
